name: Building package automation 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3' 

      - name: Run Infinity script
        run: |
          chmod +x ./Infinity
          for Dir in ./Build/*; 
            ./Infinity build "$Dir"
          fi
          done
